# Plumar 配置文件
# 基于 Hexo 配置格式设计，简洁实用

# 站点信息
title: "{{siteName}}"
subtitle: ""
description: "基于 Astro 和 Plumar 的博客站点"
keywords: []
author: ""
language: "zh-CN"
timezone: "Asia/Shanghai"

# URL 配置
url: "https://your-site.com"
root: "/"
permalink: ":year/:month/:day/:title/"

# 目录配置
source_dir: "src/content/blog"
public_dir: "dist"

# 写作配置
new_post_name: ":year-:month-:day-:title.md"
default_layout: "post"
filename_case: 0
render_drafts: false

# 分类和标签
default_category: "未分类"
category_map: {}
tag_map: {}

# 日期时间格式
date_format: "YYYY-MM-DD"
time_format: "HH:mm:ss"

# 分页配置
per_page: 10
pagination_dir: "page"

# 扩展配置
theme: "2025Plumar"
theme_config: {}
deploy: {} 